version: '3.8'

services:
  app:
    entrypoint: ["./docker/php/entrypoint.sh"]
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: '${UID:-1000}'  # UID do host
        GROUP_ID: '${GID:-1000}'  # GID do host
    container_name: clean-code-laravel
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_app
    expose:
      - 9004
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=localhost

  webserver:
    image: nginx:latest
    container_name: st-nginx
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel_app

  db:
      image: postgres:16
      container_name: st-postgres
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
      ports:
          - "5432:5432"
      volumes:
          - pgdata:/var/lib/postgresql/data
      networks:
          - laravel_app

  minio:
    image: minio/minio
    container_name: st-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data
    networks:
      - laravel_app


networks:
  laravel_app:
    driver: bridge

volumes:
    pgdata:
    miniodata:
